version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0
  snyk: snyk/snyk@1.1.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    resource_class: large
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
      - run: sudo apt-get update
      - run: sudo apt-get install openssh-client
      - add_ssh_keys:
          fingerprints:
            - "fb:80:9e:b3:ad:15:55:54:46:3d:f1:35:f3:bf:44:1f"
      - run: mkdir -p -m 0600 ~/.ssh && ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
      - restore_cache:
          key: yarn-v4-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: node-v4-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: yarn-v4-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v4-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - public

  scan:
    docker:
      - image: cimg/node:12.16
    steps:
      - run: cd / && ls
      - run: ls
      - attach_workspace:
          at: /home/circleci
      - run: ls
      - run: sudo npm install -g sonarqube-scanner
      - run: sudo sonar-scanner -D sonar.organization=$SONAR_ORG_KEY -D sonar.host.url=$SONAR_HOST_URL -D sonar.projectKey=$SONAR_PROJECT_KEY -D sonar.login=$SONAR_TOKEN -D sonar.branch.name=$CIRCLE_BRANCH

  upload:
    docker:
      - image: cimg/python:3.6
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y p7zip-full
      - attach_workspace:
          at: /tmp/workspace
      - run: 7z a -p$AWS_ZIP_PW kagr-portal-ui.zip /tmp/workspace/public/*
      - aws-s3/copy:
          from: kagr-portal-ui.zip
          to: '$AWS_ACCESS_URL/$CIRCLE_BRANCH/'

  secure:
    docker:
      - image: cimg/node:12.16
    steps:
      - attach_workspace:
          at: /home/circleci
      - restore_cache:
          key: yarn-v4-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: node-v4-{{ checksum "package.json" }}
      - run: yarn install
      - snyk/scan:
          fail-on-issues: false
          additional-arguments: '--remote-repo-url="$CIRCLE_PROJECT_REPONAME"'
          organization: '$SNYK_ORG'
          project: '$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH'

workflows:
  build-deploy:
    jobs:
      - build:
          context: builds
      - scan:
          context: builds
          requires:
            - build
      - secure:
          context: builds
          requires:
            - build
      - upload:
          context: builds
          requires:
            - build

