version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

jobs:
  build:
    working_directory: /src
    docker:
      - image: node:12.16-alpine
    steps:
      - checkout
      - run: apk update
      - run: apk add --no-cache openssh-client git
      - add_ssh_keys:
          fingerprints:
            - "fb:80:9e:b3:ad:15:55:54:46:3d:f1:35:f3:bf:44:1f"
      - run: mkdir -p -m 0600 ~/.ssh && ssh-keyscan -t rsa bitbucket.org >> ~/.ssh/known_hosts
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: /src
          paths:
            - public

  upload:
    docker:
      - image: cimg/python:3.6
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y p7zip-full
      - attach_workspace:
          at: /tmp/workspace
      - run: 7z a kagr-portal-ui.zip /tmp/workspace/public/*
      - aws-s3/copy:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-region: $AWS_REGION
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          from: kagr-portal-ui.zip
          to: 's3://vecd-snaplogic/test/'

workflows:
  build-deploy:
    jobs:
      - build
      - upload:
          requires:
            - build
