version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0
  snyk: snyk/snyk@1.1.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    resource_class: large
    steps:
      - checkout
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project
      - run: sudo apt-get update -y
      - run: sudo apt-get install ssh -y
      - restore_cache:
          key: yarn-v3-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: node-v3-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: yarn-v3-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v3-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn build
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - public

  scan:
    docker:
      - image: cimg/node:12.16
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: sudo npm install -g sonarqube-scanner
      - run: sonar-scanner -D sonar.organization="$SONAR_ORG_KEY" -D sonar.host.url="$SONAR_HOST_URL" -D sonar.projectKey="$SONAR_PROJECT_KEY" -D sonar.login="$SONAR_TOKEN" -D sonar.branch.name="$CIRCLE_BRANCH"

  upload:
    docker:
      - image: cimg/python:3.6
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y p7zip-full
      - attach_workspace:
          at: /tmp/workspace
      - run: 7z a kagr-portal-ui.zip /tmp/workspace/public/*
      - aws-s3/copy:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: kagr-portal-ui.zip
          to: 's3://vecd-snaplogic/test/'

  secure:
    docker:
      - image: cimg/node:12.16
    steps:
      - attach_workspace:
          at: /home/circleci
      - run: yarn install
      - snyk/scan:
          fail-on-issues: false
          additional-arguments: '--remote-repo-url="${CIRCLE_PROJECT_REPONAME}"'
          organization: '${SNYK_ORG}'
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}'

workflows:
  build-deploy:
    jobs:
      - build
      - secure:
          context: builds
          requires:
            - build
